version: "3"

services:

  express:
    image: node:alpine
    container_name: express
    volumes:
      - ./app:/app
    working_dir: /app
    command: >
      sh -c "
        npm install -g nodemon &&
        npm install &&
        nodemon app
      "
    tty: true
    ports:
      - "8080:8080"